version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - backend

  backend:
    ports:
      - "3000:3000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: cashforce_v3
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
